-- 테이블 생성
CREATE TABLE AUTH_NAMES
(
  AUTH_NAME VARCHAR(200) NULL     COMMENT '접근권한',
  UNIQUE_ID VARCHAR(200) NOT NULL COMMENT '접근권한 대표값',
  PRIMARY KEY (UNIQUE_ID)
) COMMENT '접근권한명';

CREATE TABLE AUTHS
(
  UNIQUE_ID_USERS      VARCHAR(200) NOT NULL COMMENT '대표값',
  UNIQUE_ID_AUTH_NAMES VARCHAR(200) NOT NULL COMMENT '접근권한 대표값'
) COMMENT '권한들';

CREATE TABLE USERS
(
  UNIQUE_ID VARCHAR(200) NOT NULL COMMENT '대표값',
  NAME      VARCHAR(200) NULL     COMMENT '이름',
  EMAIL     VARCHAR(200) NULL     COMMENT '이메일',
  JOB       VARCHAR(200) NULL     COMMENT '직책',
  PRIMARY KEY (UNIQUE_ID)
) COMMENT '사용자들';

ALTER TABLE AUTHS
  ADD CONSTRAINT FK_USERS_TO_AUTHS
    FOREIGN KEY (UNIQUE_ID_USERS)
    REFERENCES USERS (UNIQUE_ID);

ALTER TABLE AUTHS
  ADD CONSTRAINT FK_AUTH_NAMES_TO_AUTHS
    FOREIGN KEY (UNIQUE_ID_AUTH_NAMES)
    REFERENCES AUTH_NAMES (UNIQUE_ID);



-- users 회원가입
INSERT INTO users(UNIQUE_ID, NAME, EMAIL, JOB)
VALUE ('U1', 'Paul', 'paul01@gmail.com', 'IT Billing')
;
INSERT INTO users(UNIQUE_ID, NAME, EMAIL, JOB)
VALUE ('U2', 'Allen', 'texas@imfblog.org', 'Engineering')
;
INSERT INTO users(UNIQUE_ID, NAME, EMAIL, JOB)
VALUE ('U3', 'Teddy', 'norway@iotm.com', 'IT Billing')
;
INSERT INTO users(UNIQUE_ID, NAME, EMAIL, JOB)
VALUE ('U4', 'Paul', 'paul_p@naver.com', 'Developer')
;

-- auth 접근권한
INSERT auth_names(AUTH_NAME, UNIQUE_ID)
VALUE ('GUEST', 'B1')
;
INSERT auth_names(AUTH_NAME, UNIQUE_ID)
VALUE ('ADMIN', 'B2')
;
INSERT auth_names(AUTH_NAME, UNIQUE_ID)
VALUE ('MANAGER', 'B3')
;

-- 접근권한들
INSERT auths(UNIQUE_ID_USERS, UNIQUE_ID_AUTH_NAMES)
VALUE ('U1', 'B1')
;
INSERT auths(UNIQUE_ID_USERS, UNIQUE_ID_AUTH_NAMES)
VALUE ('U1', 'B2')
;
INSERT auths(UNIQUE_ID_USERS, UNIQUE_ID_AUTH_NAMES)
VALUE ('U2', 'B1')
;
INSERT auths(UNIQUE_ID_USERS, UNIQUE_ID_AUTH_NAMES)
VALUE ('U2', 'B2')
;
INSERT auths(UNIQUE_ID_USERS, UNIQUE_ID_AUTH_NAMES)
VALUE ('U2', 'B3')
;
INSERT auths(UNIQUE_ID_USERS, UNIQUE_ID_AUTH_NAMES)
VALUE ('U3', 'B1')
;
INSERT auths(UNIQUE_ID_USERS, UNIQUE_ID_AUTH_NAMES)
VALUE ('U4', 'B1')
;
INSERT auths(UNIQUE_ID_USERS, UNIQUE_ID_AUTH_NAMES)
VALUE ('U4', 'B2')
;

-- 회원 탈퇴
DELETE FROM auths
WHERE UNIQUE_ID_USERS = 'U2'
;
DELETE FROM auths
WHERE UNIQUE_ID_USERS = 'U4'
;

DELETE FROM users
WHERE UNIQUE_ID = 'U2'
;
DELETE FROM users
WHERE UNIQUE_ID = 'U4'
;

-- ---------------

-- table 확인
SELECT *
FROM users
;

SELECT *
FROM auth_names
;

SELECT *
FROM auths
;
